GET http://localhost:3000/api/products

###
GET http://localhost:3000/api/products/v2

###
GET http://localhost:3000/api/products/5

###
POST http://localhost:3000/api/products/v2
Content-Type: application/json

{
    "name": "Pantalón de pana",
    "description": "Mu fresquito",
    "price": 60,
    "category": "moda"
}

###
PUT http://localhost:3000/api/products/5
Content-Type: application/json

{
    "name": "Pantalón de pana",
    "description": "Mu fresquito para el veranito",
    "price": 170,
    "category": "moda"
}

###
DELETE http://localhost:3000/api/products/3

###1
GET http://localhost:3000/api/products/cat/moda

###
GET http://localhost:3000/api/clients

###
POST http://localhost:3000/api/clients

###
POST http://localhost:3000/api/users/register
Content-Type: application/json

{
    "username": "mario",
    "email": "mario6@gmail.com",
    "password": "12345"
}